spring:
  application:
    name: jobtrack
  datasource:
    url: jdbc:postgresql://localhost:5432/jobtrackdb
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration  