spring:
  application:
    name: jobtrack
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jobtrackdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration

jwt:
  secret: ${JWT_SECRET:changeitchangeitchangeitchangeitchangeit}
  expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}
